name: Metrics

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/metrics.yml

permissions:
  contents: write

concurrency:
  group: metrics
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Generate Engineering Metrics
        uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: yes
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          output_action: commit
          committer_branch: output
          committer_message: "chore: update github-metrics.svg [skip ci]"
          
          # Base layout
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Almaty
          config_order: base.header, languages, notable, followup
          
          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming, data
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          
          # Notable contributions
          plugin_notable: yes
          plugin_notable_types: commit, pull_request
          plugin_notable_from: all
          
          # Issues and Pull Requests follow-up
          plugin_followup: yes
          plugin_followup_sections: user, repositories
